### ISSUE TITLE
various compatibility issues

### ISSUE THREAD

**Issue by errordeveloper** [hyperhq/hypercli#184]
The following file works fine with Docker:
```YAML
version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    restart: always
  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
    hostname: edge-router
    restart: always
  catalogue:
    image: weaveworksdemos/catalogue
    hostname: catalogue
    restart: always
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    restart: always
  cart-db:
    image: mongo
    hostname: cart-db
    restart: always
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    restart: always
  orders-db:
    image: mongo
    hostname: orders-db
    restart: always
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    restart: always
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    restart: always
  payment:
    image: weaveworksdemos/payment
    hostname: payment
    restart: always
  user:
    image: weaveworksdemos/user
    hostname: user
    restart: always
    environment:
      - MONGO_HOST=user-db:27017
  user-db:
    image: weaveworksdemos/user-db
    hostname: user-db
    restart: always
  user-sim:
    image: weaveworksdemos/load-test
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"
```

However, it doesn't just work with `hyper compose up -d`. I had to start containers individually with `hyper compose up -p sockshop -d <container-name>`.

The `orders` and `cart` containers consistently fail to start with:
```
Error response from daemon: No command specified
```

Also,  I've seen this error appeared randomly:
```
Error response from daemon: Rbd device 426d65c74af472be4c0bbe442f5c0b03ca258dcb827ebc50f45ef8f39e3b5526 does not exist
```
