### ISSUE TITLE
hyper compose up container recreation fails

### ISSUE THREAD

**Issue by msokk** [hyperhq/hypercli#190]
I'm trying to run `hyper compose up -d --force-recreate -f hyper-compose.yml` or just `hyper compose up -d -f hyper-compose.yml` (when the image has changed).

The command fails with following output

```
(This is an existing compose project)
Project [atelierapi]: Starting project
[1/2] [db]: Starting
[1/2] [db]: Started
[2/2] [app]: Starting
The dotted field 'sh.hyper.compose.project' in 'base.config.labels.sh.hyper.compose.project' is not valid for storage.
```

The last line varies between some container labels like - `project`, `service`, `version`, `oneoff`.

Mentioned labels from `hyper inspect` look like this:
```
"sh.hyper.compose.oneoff": "False",
"sh.hyper.compose.project": "atelierapi",
"sh.hyper.compose.service": "app",
"sh.hyper.compose.version": "1.5.0",
```

My hyper-compose.yml (`CI_ENVIRONMENT_SLUG` value was `preview`):
```yml
version: '2'
services:
  app:
    hostname: "atelier-api-${CI_ENVIRONMENT_SLUG}"
    size: s2
    image: registry.gitlab.com/mokoko/atelier_api
    links:
      - db
    ports:
      - "3000:3000"

  db:
    hostname: "atelier-db-${CI_ENVIRONMENT_SLUG}"
    size: s2
    image: mokoko/postgres
    volumes:
      - "atelier-${CI_ENVIRONMENT_SLUG}-db:/var/lib/postgresql/data"
```
